version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8000 --key-file key.pem --cert-file cert.pem
    volumes:
      - .:/app
      - db_data:/app/data
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - GEOCODING_API_KEY=
    #   - DATABASE_PATH=/app/data/db.sqlite3
    #   - ADMIN_USERNAME=admin
    #   - ADMIN_PASSWORD=fenfesta

volumes:
  db_data: