# Generated by Django 5.0.6 on 2024-05-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
