# Generated by Django 5.0.6 on 2024-05-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_capacity_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='user_id',
        ),
    ]
