# Generated by Django 5.0.6 on 2024-05-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_event_reservation_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
    ]
